/**
 * demoScenarios.ts
 *
 * Centralized demo/mock data for offline showcase.
 * Used as fallback when Supabase is unavailable or via Dev Pass bypass.
 */

import { VitalisEvent } from '../services/eventService';
import { Club, Conference, Match, Profile, MedicalRole, Specialty, Notification, NotificationType, SwipeHistoryItem, MessageStatus } from '../types';

// ─── Helpers ──────────────────────────────────────────────────────────────────

const minutesAgo = (m: number) => Date.now() - m * 60_000;
const hoursAgo = (h: number) => Date.now() - h * 3_600_000;
const hoursFromNow = (h: number) => Date.now() + h * 3_600_000;
const daysFromNow = (d: number) => {
    const date = new Date();
    date.setDate(date.getDate() + d);
    return date.toISOString();
};
const daysAgo = (d: number) => Date.now() - d * 86_400_000;

// ─── DEMO PROFILES ────────────────────────────────────────────────────────────

export const DEMO_PROFILES: Profile[] = [
    {
        id: 'demo-1',
        name: 'Dr. Elif',
        age: 29,
        role: MedicalRole.DOCTOR,
        specialty: Specialty.CARDIOLOGY,
        subSpecialty: 'Girişimsel Kardiyoloji',
        hospital: 'Acıbadem Maslak Hastanesi',
        institutionHidden: false,
        bio: 'Kalpleri hem ameliyatta hem hayatta iyileştiriyorum. Kitap tutkunu, doğa aşığı. Ciddi bir ilişki arıyorum.',
        education: 'Hacettepe Tıp Fakültesi',
        genderPreference: 'MALE',
        university: 'Hacettepe Üniversitesi',
        city: 'Istanbul',
        graduationYear: 2019,
        experienceYears: 7,
        lookingFor: 'SERIOUS',
        smoking: 'NO',
        drinking: 'SOCIAL',
        images: [
            'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=800&h=1200&fit=crop',
            'https://images.unsplash.com/photo-1594824476967-48c8b964ac31?w=800&h=1200&fit=crop',
        ],
        verified: true,
        verificationBadges: { photo: true, phone: true, email: true, license: true },
        interests: ['Kardiyoloji', 'Yoga', 'Trekking', 'Kahve', 'Fotoğrafçılık'],
        personalityTags: ['soc_3', 'life_3', 'rel_1', 'hum_2'],
        questions: [
            { id: 'q1', question: 'En sevdiğim kahve çeşidi...', answer: 'Yulaf sütlü Flat White, karamelli.' },
            { id: 'q2', question: 'Hafta sonu idealim...', answer: 'Belgrad Ormanı\'nda yürüyüş ve brunch.' },
            { id: 'q3', question: 'Nöbet sonrası ilk yaptığım şey...', answer: 'Kesintisiz 10 saat uyku!' },
        ],
        hasLikedUser: true,
        distance: 2.3,
        location: 'Beşiktaş',
        isLocationHidden: false,
        lastActive: minutesAgo(5),
        isOnlineHidden: false,
        isAvailable: true,
        availabilityExpiresAt: hoursFromNow(4),
        readReceiptsEnabled: true,
        stories: [],
        storyPrivacy: 'ALL_MATCHES',
    },
    {
        id: 'demo-2',
        name: 'Dr. Kaan',
        age: 33,
        role: MedicalRole.DOCTOR,
        specialty: Specialty.SURGERY,
        subSpecialty: 'Beyin ve Sinir Cerrahisi',
        hospital: 'Florence Nightingale Hastanesi',
        institutionHidden: false,
        bio: 'Ameliyathane ve mutfak arasında gidip geliyorum. İyi bir yemek ve güzel bir sohbete bayılırım.',
        education: 'Cerrahpaşa Tıp Fakültesi',
        genderPreference: 'FEMALE',
        university: 'İstanbul Üniversitesi',
        city: 'Istanbul',
        graduationYear: 2017,
        experienceYears: 9,
        lookingFor: 'SERIOUS',
        smoking: 'NO',
        drinking: 'SOCIAL',
        images: [
            'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=800&h=1200&fit=crop',
            'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=800&h=1200&fit=crop',
        ],
        verified: true,
        verificationBadges: { photo: true, phone: true, email: true, license: true },
        interests: ['Cerrahi', 'Yemek', 'Şarap', 'Dalış', 'Felsefe'],
        personalityTags: ['soc_1', 'life_2', 'rel_1', 'hum_3'],
        questions: [
            { id: 'q1', question: 'Stresten kurtulmak için...', answer: 'Yeni tarifler deniyorum, fusion mutfak favorim.' },
            { id: 'q2', question: 'Hayalindeki tatil...', answer: 'Japonya\'da bir sushi atölyesi.' },
        ],
        hasLikedUser: false,
        distance: 5.1,
        location: 'Şişli',
        isLocationHidden: false,
        lastActive: minutesAgo(30),
        isOnlineHidden: false,
        isAvailable: false,
        readReceiptsEnabled: true,
        stories: [],
        storyPrivacy: 'ALL_MATCHES',
    },
    {
        id: 'demo-3',
        name: 'Dr. Zeynep',
        age: 27,
        role: MedicalRole.DOCTOR,
        specialty: Specialty.DERMATOLOGY,
        subSpecialty: 'Kozmetik Dermatoloji',
        hospital: 'Memorial Şişli Hastanesi',
        institutionHidden: false,
        bio: 'Cilt sağlığı konusunda tutkuluyum. Boş zamanlarımda pilates, dans, ve açık hava etkinlikleri. Enerjik ve pozitif birini arıyorum!',
        education: 'GATA Tıp Fakültesi',
        genderPreference: 'MALE',
        university: 'Gülhane Üniversitesi',
        city: 'Istanbul',
        graduationYear: 2021,
        experienceYears: 5,
        lookingFor: 'SERIOUS',
        smoking: 'NO',
        drinking: 'NO',
        images: [
            'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=800&h=1200&fit=crop',
            'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=800&h=1200&fit=crop',
        ],
        verified: true,
        verificationBadges: { photo: true, phone: true, email: true, license: true },
        interests: ['Dermatoloji', 'Pilates', 'Salsa', 'Seyahat', 'Fotoğrafçılık'],
        personalityTags: ['soc_2', 'life_1', 'rel_1', 'hum_1'],
        questions: [
            { id: 'q1', question: 'Beni güldüren şey...', answer: 'Beklenmedik espri anlayışı olan insanlar.' },
            { id: 'q2', question: 'Favori nöbet atıştırmalığım...', answer: 'Kuru karamelize badem ve yeşil çay.' },
            { id: 'q3', question: 'Hafta sonu idealim...', answer: 'Sahilde koşu, akşam canlı müzik.' },
        ],
        hasLikedUser: true,
        distance: 1.8,
        location: 'Kadıköy',
        isLocationHidden: false,
        lastActive: minutesAgo(12),
        isOnlineHidden: false,
        isAvailable: true,
        availabilityExpiresAt: hoursFromNow(2),
        readReceiptsEnabled: true,
        stories: [],
        storyPrivacy: 'ALL_MATCHES',
    },
    {
        id: 'demo-4',
        name: 'Dr. Berk',
        age: 31,
        role: MedicalRole.DOCTOR,
        specialty: Specialty.SURGERY,
        subSpecialty: 'Spor Hekimliği',
        hospital: 'Liv Hospital',
        institutionHidden: true,
        bio: 'Sporcuların iyileşme sürecinde yanlarındayım. Kendim de aktif bir sporcu sayılırım — koşu, yüzme, tırmanış.',
        education: 'Ankara Üniversitesi Tıp',
        genderPreference: 'FEMALE',
        university: 'Ankara Üniversitesi',
        city: 'Istanbul',
        graduationYear: 2018,
        experienceYears: 8,
        lookingFor: 'OPEN',
        smoking: 'NO',
        drinking: 'SOCIAL',
        images: [
            'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=800&h=1200&fit=crop',
            'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=800&h=1200&fit=crop',
        ],
        verified: true,
        verificationBadges: { photo: true, phone: true, email: true, license: true },
        interests: ['Ortopedi', 'Koşu', 'Yüzme', 'Tırmanış', 'Müzik'],
        personalityTags: ['soc_1', 'life_4', 'rel_3', 'hum_2'],
        questions: [
            { id: 'q1', question: 'Stresten kurtulmak için...', answer: 'Kulaklığımı takıp sahil koşusu.' },
            { id: 'q2', question: 'Hayalindeki tatil...', answer: 'Alpler\'de tırmanış ve kayak tatili.' },
        ],
        hasLikedUser: false,
        distance: 8.2,
        location: 'Bebek',
        isLocationHidden: false,
        lastActive: hoursAgo(1),
        isOnlineHidden: false,
        isAvailable: true,
        availabilityExpiresAt: hoursFromNow(3),
        readReceiptsEnabled: true,
        stories: [],
        storyPrivacy: 'ALL_MATCHES',
    },
    {
        id: 'demo-5',
        name: 'Dr. Defne',
        age: 30,
        role: MedicalRole.DOCTOR,
        specialty: Specialty.PEDIATRICS,
        subSpecialty: 'Neonatoloji',
        hospital: 'Anadolu Sağlık Merkezi',
        institutionHidden: false,
        bio: 'Yeni doğanların ilk nefeslerine tanıklık ediyorum. Hayata dair tutkum, mesleğimden başlıyor.',
        education: 'Ege Üniversitesi Tıp',
        genderPreference: 'MALE',
        university: 'Ege Üniversitesi',
        city: 'Istanbul',
        graduationYear: 2020,
        experienceYears: 6,
        lookingFor: 'SERIOUS',
        smoking: 'NO',
        drinking: 'NO',
        images: [
            'https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?w=800&h=1200&fit=crop',
            'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&h=1200&fit=crop',
        ],
        verified: true,
        verificationBadges: { photo: true, phone: true, email: true, license: true },
        interests: ['Pediatri', 'Resim', 'Kitap', 'Doğa', 'Gönüllülük'],
        personalityTags: ['soc_3', 'life_1', 'rel_1', 'hum_1'],
        questions: [
            { id: 'q1', question: 'Beni güldüren şey...', answer: 'Çocukların masumiyeti ve beklenmedik tepkileri.' },
            { id: 'q2', question: 'Hafta sonu idealim...', answer: 'Bir gönüllülük projesi ve akşam resim yapma.' },
        ],
        hasLikedUser: true,
        distance: 3.5,
        location: 'Üsküdar',
        isLocationHidden: false,
        lastActive: minutesAgo(8),
        isOnlineHidden: false,
        isAvailable: false,
        readReceiptsEnabled: true,
        stories: [],
        storyPrivacy: 'ALL_MATCHES',
    },
    {
        id: 'demo-6',
        name: 'Dr. Emre',
        age: 35,
        role: MedicalRole.DOCTOR,
        specialty: Specialty.PSYCHIATRY,
        subSpecialty: 'Bağımlılık Psikiyatrisi',
        hospital: 'Koç Üniversitesi Hastanesi',
        institutionHidden: false,
        bio: 'İnsan zihninin karmaşıklığı beni büyüler. Sanatla, müzikle ve derin sohbetlerle besleniyorum.',
        education: 'İstanbul Tıp Fakültesi',
        genderPreference: 'FEMALE',
        university: 'İstanbul Üniversitesi',
        city: 'Istanbul',
        graduationYear: 2015,
        experienceYears: 11,
        lookingFor: 'SERIOUS',
        smoking: 'NO',
        drinking: 'SOCIAL',
        images: [
            'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=800&h=1200&fit=crop',
            'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=1200&fit=crop',
        ],
        verified: true,
        verificationBadges: { photo: true, phone: true, email: true, license: true },
        interests: ['Psikiyatri', 'Caz', 'Edebiyat', 'Sinema', 'Felsefe'],
        personalityTags: ['soc_2', 'life_3', 'rel_1', 'hum_3'],
        questions: [
            { id: 'q1', question: 'En sevdiğim kahve çeşidi...', answer: 'V60 pour-over, Etiyopya orijin.' },
            { id: 'q2', question: 'Stresten kurtulmak için...', answer: 'Piyano çalarım, bazen saatlerce.' },
        ],
        hasLikedUser: false,
        distance: 4.7,
        location: 'Sarıyer',
        isLocationHidden: false,
        lastActive: hoursAgo(2),
        isOnlineHidden: false,
        isAvailable: false,
        readReceiptsEnabled: true,
        stories: [],
        storyPrivacy: 'ALL_MATCHES',
    },
    {
        id: 'demo-7',
        name: 'Dr. Selin',
        age: 28,
        role: MedicalRole.DOCTOR,
        specialty: Specialty.NEUROLOGY,
        subSpecialty: 'Klinik Nörofizyoloji',
        hospital: 'Cerrahpaşa Tıp Fakültesi',
        institutionHidden: false,
        bio: 'Beyni keşfetmek benim için bir tutku. Geri kalan zamanlarda dans, meditasyon ve yeni tatlar denemek.',
        education: 'Cerrahpaşa Tıp',
        genderPreference: 'MALE',
        university: 'İstanbul Üniversitesi-Cerrahpaşa',
        city: 'Istanbul',
        graduationYear: 2022,
        experienceYears: 4,
        lookingFor: 'SERIOUS',
        smoking: 'NO',
        drinking: 'SOCIAL',
        images: [
            'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=800&h=1200&fit=crop',
            'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&h=1200&fit=crop',
        ],
        verified: true,
        verificationBadges: { photo: true, phone: true, email: true, license: true },
        interests: ['Nörobilim', 'Meditasyon', 'Dans', 'Yemek', 'Podcast'],
        personalityTags: ['soc_3', 'life_2', 'rel_1', 'hum_2'],
        questions: [
            { id: 'q1', question: 'Beni güldüren şey...', answer: 'Absürd komedi ve beklenmedik benzetmeler.' },
            { id: 'q2', question: 'Nöbet sonrası ilk yaptığım şey...', answer: 'Sıcak bir duş ve film maratonu.' },
        ],
        hasLikedUser: true,
        distance: 6.1,
        location: 'Fatih',
        isLocationHidden: false,
        lastActive: minutesAgo(20),
        isOnlineHidden: false,
        isAvailable: true,
        availabilityExpiresAt: hoursFromNow(5),
        readReceiptsEnabled: true,
        stories: [],
        storyPrivacy: 'ALL_MATCHES',
    },
    {
        id: 'demo-8',
        name: 'Dr. Cem',
        age: 36,
        role: MedicalRole.DOCTOR,
        specialty: Specialty.RADIOLOGY,
        subSpecialty: 'İnterventional Radyoloji',
        hospital: 'Amerikan Hastanesi',
        institutionHidden: false,
        bio: 'Görüntülerin arkasındaki hikâyeyi okuyorum. Fotoğrafçılık, teknoloji ve uzun motosiklet turlarının tutkunu.',
        education: 'Marmara Tıp Fakültesi',
        genderPreference: 'FEMALE',
        university: 'Marmara Üniversitesi',
        city: 'Istanbul',
        graduationYear: 2014,
        experienceYears: 12,
        lookingFor: 'SERIOUS',
        smoking: 'NO',
        drinking: 'SOCIAL',
        images: [
            'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=1200&fit=crop',
            'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&h=1200&fit=crop',
        ],
        verified: true,
        verificationBadges: { photo: true, phone: true, email: true, license: true },
        interests: ['Radyoloji', 'Fotoğrafçılık', 'Motosiklet', 'Teknoloji', 'Kahve'],
        personalityTags: ['soc_1', 'life_4', 'rel_2', 'hum_3'],
        questions: [
            { id: 'q1', question: 'En sevdiğim kahve çeşidi...', answer: 'Cold brew, sade, buz gibi.' },
            { id: 'q2', question: 'Hayalindeki tatil...', answer: 'İskandinav ülkelerinde motosiklet turu.' },
        ],
        hasLikedUser: false,
        distance: 10.4,
        location: 'Nişantaşı',
        isLocationHidden: false,
        lastActive: hoursAgo(3),
        isOnlineHidden: false,
        isAvailable: false,
        readReceiptsEnabled: true,
        stories: [],
        storyPrivacy: 'ALL_MATCHES',
    },
];

// ─── DEMO EVENTS ──────────────────────────────────────────────────────────────

export const DEMO_EVENTS: VitalisEvent[] = [
    {
        id: 'evt-1',
        title: 'Sağlık Profesyonelleri Kahve Buluşması',
        description: 'İstanbul Kadıköy\'de sağlık sektöründe çalışan profesyoneller için rahat bir networking etkinliği. Latte ve espresso eşliğinde yeni bağlantılar kurun.',
        event_type: 'coffee',
        cover_image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&h=500&fit=crop',
        location_name: 'Petra Roasting Co.',
        location_address: 'Caferağa Mah., Moda Cad. No:54, Kadıköy',
        location_lat: 40.9879,
        location_lng: 29.0265,
        city: 'Istanbul',
        district: 'Kadıköy',
        starts_at: daysFromNow(1),
        ends_at: daysFromNow(1),
        max_attendees: 20,
        current_attendees: 14,
        is_verified_only: false,
        is_premium_only: false,
        created_by: null,
        is_active: true,
        created_at: new Date().toISOString(),
    },
    {
        id: 'evt-2',
        title: 'Boğaz Kıyısı Sabah Koşusu',
        description: 'Beşiktaş-Ortaköy güzergâhında haftalık sabah koşusu. Tüm seviyelere açık, tempo 5:30-6:30/km. Koşu sonrası kahvaltı dahil!',
        event_type: 'activity',
        cover_image: 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800&h=500&fit=crop',
        location_name: 'Beşiktaş Sahil Parkı',
        location_address: 'Sinanpaşa Mah., Beşiktaş Sahili',
        location_lat: 41.0422,
        location_lng: 29.0034,
        city: 'Istanbul',
        district: 'Beşiktaş',
        starts_at: daysFromNow(2),
        ends_at: daysFromNow(2),
        max_attendees: 30,
        current_attendees: 22,
        is_verified_only: true,
        is_premium_only: false,
        created_by: null,
        is_active: true,
        created_at: new Date().toISOString(),
    },
    {
        id: 'evt-3',
        title: 'Vitalis Elite Gala Gecesi',
        description: 'Sadece premium üyelere özel, The Ritz-Carlton\'da düzenlenen gala gecesi. Canlı caz müziği, özel menü ve networking fırsatları.',
        event_type: 'meetup',
        cover_image: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&h=500&fit=crop',
        location_name: 'The Ritz-Carlton, Istanbul',
        location_address: 'Süzer Plaza, Askerocağı Cad. No:6, Şişli',
        location_lat: 41.0473,
        location_lng: 28.9904,
        city: 'Istanbul',
        district: 'Şişli',
        starts_at: daysFromNow(5),
        ends_at: daysFromNow(5),
        max_attendees: 80,
        current_attendees: 63,
        is_verified_only: true,
        is_premium_only: true,
        created_by: null,
        is_active: true,
        created_at: new Date().toISOString(),
    },
    {
        id: 'evt-4',
        title: 'Belgrad Ormanı Doğa Yürüyüşü',
        description: 'Doktorlar ve sağlık profesyonelleri için hafta sonu doğa yürüyüşü. 12 km parkur, zorluk: orta. Su ve enerji barı sağlanacaktır.',
        event_type: 'walk',
        cover_image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&h=500&fit=crop',
        location_name: 'Belgrad Ormanı Giriş',
        location_address: 'Bahçeköy Yolu, Sarıyer',
        location_lat: 41.1708,
        location_lng: 28.9772,
        city: 'Istanbul',
        district: 'Sarıyer',
        starts_at: daysFromNow(3),
        ends_at: daysFromNow(3),
        max_attendees: 25,
        current_attendees: 18,
        is_verified_only: false,
        is_premium_only: false,
        created_by: null,
        is_active: true,
        created_at: new Date().toISOString(),
    },
    {
        id: 'evt-5',
        title: 'Tıp Dünyası Speed Dating',
        description: 'Sağlık profesyonelleri için özel speed dating etkinliği. 8 dakikalık görüşmeler, maksimum 12 eşleşme. Premium bar hizmeti.',
        event_type: 'micro_event',
        cover_image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&h=500&fit=crop',
        location_name: 'Soho House Istanbul',
        location_address: 'Meşrutiyet Cad. No:56, Beyoğlu',
        location_lat: 41.0311,
        location_lng: 28.9747,
        city: 'Istanbul',
        district: 'Beyoğlu',
        starts_at: daysFromNow(4),
        ends_at: daysFromNow(4),
        max_attendees: 24,
        current_attendees: 20,
        is_verified_only: true,
        is_premium_only: false,
        created_by: null,
        is_active: true,
        created_at: new Date().toISOString(),
    },
    {
        id: 'evt-6',
        title: 'Kardiyoloji & Nörobilim Paneli',
        description: 'İstanbul\'un önde gelen kardiyologları ve nörologlarıyla panel. Beyin-kalp bağlantısı üzerine güncel araştırmalar tartışılacak.',
        event_type: 'conference',
        cover_image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=500&fit=crop',
        location_name: 'İstanbul Kongre Merkezi',
        location_address: 'Darülbedayi Cad., Harbiye',
        location_lat: 41.0476,
        location_lng: 28.9934,
        city: 'Istanbul',
        district: 'Şişli',
        starts_at: daysFromNow(6),
        ends_at: daysFromNow(6),
        max_attendees: 200,
        current_attendees: 147,
        is_verified_only: false,
        is_premium_only: false,
        created_by: null,
        is_active: true,
        created_at: new Date().toISOString(),
    },
    {
        id: 'evt-7',
        title: 'Caddebostan Plaj Voleybolu',
        description: 'Her Cumartesi sağlık çalışanları arasında plaj voleybolu turnuvası. Tüm seviyeler hoş geldiniz!',
        event_type: 'activity',
        cover_image: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800&h=500&fit=crop',
        location_name: 'Caddebostan Sahili',
        location_address: 'Caddebostan Mahallesi, Kadıköy',
        location_lat: 40.9641,
        location_lng: 29.0574,
        city: 'Istanbul',
        district: 'Kadıköy',
        starts_at: daysFromNow(2),
        ends_at: daysFromNow(2),
        max_attendees: 16,
        current_attendees: 12,
        is_verified_only: false,
        is_premium_only: false,
        created_by: null,
        is_active: true,
        created_at: new Date().toISOString(),
    },
    {
        id: 'evt-8',
        title: 'Nişantaşı Wine & Cheese Akşamı',
        description: 'Premium üyelere özel, uzman sommelier eşliğinde özenle seçilmiş şaraplar ve peynir tadımı.',
        event_type: 'meetup',
        cover_image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&h=500&fit=crop',
        location_name: 'Nişantaşı City\'s',
        location_address: 'Nişantaşı Mah., Teşvikiye Cad., Şişli',
        location_lat: 41.0504,
        location_lng: 28.9934,
        city: 'Istanbul',
        district: 'Şişli',
        starts_at: daysFromNow(7),
        ends_at: daysFromNow(7),
        max_attendees: 30,
        current_attendees: 26,
        is_verified_only: true,
        is_premium_only: true,
        created_by: null,
        is_active: true,
        created_at: new Date().toISOString(),
    },
];

// ─── DEMO CLUBS ───────────────────────────────────────────────────────────────

export const DEMO_CLUBS: Club[] = [
    {
        id: 'club-1',
        name: 'Vitalis Koşu Kulübü',
        description: 'Her hafta farklı İstanbul rotalarında koşan doktor ve sağlık profesyonelleri topluluğu. Tüm seviyelere açık!',
        category: 'running',
        creator_id: 'demo-4',
        max_members: 50,
        member_count: 34,
        is_member: false,
        city: 'Istanbul',
        cover_image: 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800&h=400&fit=crop',
        is_active: true,
        created_at: new Date(Date.now() - 30 * 86_400_000).toISOString(),
    },
    {
        id: 'club-2',
        name: 'Medikal Yoga & Mindfulness',
        description: 'Yoğun mesai sonrası zihin ve beden sağlığınız için. Haftada 2 seans, online ve yüz yüze seçenekler.',
        category: 'yoga',
        creator_id: 'demo-3',
        max_members: 40,
        member_count: 28,
        is_member: false,
        city: 'Istanbul',
        cover_image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=400&fit=crop',
        is_active: true,
        created_at: new Date(Date.now() - 60 * 86_400_000).toISOString(),
    },
    {
        id: 'club-3',
        name: 'Boğaz Bisiklet Grubu',
        description: 'Hafta sonları Boğaz boyunca bisiklet turları. Ortalama 40-60 km parkur. Yeni üyelere özel tempo grupları.',
        category: 'cycling',
        creator_id: 'demo-2',
        max_members: 30,
        member_count: 19,
        is_member: false,
        city: 'Istanbul',
        cover_image: 'https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=800&h=400&fit=crop',
        is_active: true,
        created_at: new Date(Date.now() - 45 * 86_400_000).toISOString(),
    },
    {
        id: 'club-4',
        name: 'Sağlıklı Beslenme Atölyesi',
        description: 'Beslenme uzmanları ve doktorlar eşliğinde haftalık sağlıklı yemek atölyeleri. Meal-prep teknikleri, anti-inflamatuar tarifler.',
        category: 'nutrition',
        creator_id: 'demo-1',
        max_members: 25,
        member_count: 21,
        is_member: false,
        city: 'Istanbul',
        cover_image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&h=400&fit=crop',
        is_active: true,
        created_at: new Date(Date.now() - 20 * 86_400_000).toISOString(),
    },
    {
        id: 'club-5',
        name: 'Klinik Araştırma Tartışma Grubu',
        description: 'Güncel medikal literatür ve klinik vaka tartışmaları. Ayda 2 toplantı, multidisipliner katılım.',
        category: 'research',
        creator_id: 'demo-6',
        max_members: 35,
        member_count: 27,
        is_member: false,
        city: 'Istanbul',
        cover_image: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&h=400&fit=crop',
        is_active: true,
        created_at: new Date(Date.now() - 90 * 86_400_000).toISOString(),
    },
    {
        id: 'club-6',
        name: 'Doktorlar Kayak Kulübü',
        description: 'Kış sezonunda Uludağ ve Kartalkaya turları, yaz sezonunda su sporları. Sosyal etkinlikler ve networking.',
        category: 'social',
        creator_id: 'demo-8',
        max_members: 45,
        member_count: 38,
        is_member: false,
        city: 'Istanbul',
        cover_image: 'https://images.unsplash.com/photo-1565992441121-4367c2967103?w=800&h=400&fit=crop',
        is_active: true,
        created_at: new Date(Date.now() - 120 * 86_400_000).toISOString(),
    },
];

// ─── DEMO CONFERENCES ────────────────────────────────────────────────────────

export const DEMO_CONFERENCES: Conference[] = [
    {
        id: 'conf-1',
        name: '27. Ulusal Kardiyoloji Kongresi',
        city: 'Istanbul',
        venue: 'İstanbul Kongre Merkezi, Harbiye',
        start_date: daysFromNow(10).split('T')[0],
        end_date: daysFromNow(13).split('T')[0],
        specialty_tags: ['Kardiyoloji', 'Girişimsel', 'Elektrofizyoloji'],
        max_pool_size: 500,
        is_active: true,
        created_at: new Date().toISOString(),
    },
    {
        id: 'conf-2',
        name: 'Türk Nöroloji Derneği Yıllık Toplantısı',
        city: 'Istanbul',
        venue: 'Hilton Istanbul Bomonti, Şişli',
        start_date: daysFromNow(20).split('T')[0],
        end_date: daysFromNow(23).split('T')[0],
        specialty_tags: ['Nöroloji', 'Nöroşirürji', 'Nörobilim'],
        max_pool_size: 400,
        is_active: true,
        created_at: new Date().toISOString(),
    },
    {
        id: 'conf-3',
        name: 'International Medical Innovation Summit',
        city: 'Istanbul',
        venue: 'Istanbul Expo Center, Yeşilköy',
        start_date: daysFromNow(30).split('T')[0],
        end_date: daysFromNow(32).split('T')[0],
        specialty_tags: ['Dijital Sağlık', 'Yapay Zeka', 'Biyoteknoloji'],
        max_pool_size: 800,
        is_active: true,
        created_at: new Date().toISOString(),
    },
];

// ─── DEMO MATCHES ─────────────────────────────────────────────────────────────

export const DEMO_MATCHES: Match[] = [
    {
        profile: DEMO_PROFILES[0], // Dr. Elif
        timestamp: minutesAgo(45),
        lastMessage: 'Merhaba! Kardiyoloji rotasyonun nasıl gidiyor? 😊',
        isFirstMessagePending: false,
        isActive: true,
        firstMessageSentAt: minutesAgo(40),
        messages: [
            {
                id: 'msg-1',
                text: 'Merhaba! Profilini çok beğendim, Hacettepe birlikteliği! 🎓',
                senderId: 'me',
                status: 'read' as MessageStatus,
                timestamp: minutesAgo(45),
            },
            {
                id: 'msg-2',
                text: 'Merhaba! Kardiyoloji rotasyonun nasıl gidiyor? 😊',
                senderId: 'them',
                status: 'read' as MessageStatus,
                timestamp: minutesAgo(40),
            },
        ],
    },
    {
        profile: DEMO_PROFILES[2], // Dr. Zeynep
        timestamp: hoursAgo(3),
        lastMessage: 'Cumartesi pilates sonrası kahve olur mu? ☕',
        isFirstMessagePending: false,
        isActive: true,
        firstMessageSentAt: hoursAgo(2),
        messages: [
            {
                id: 'msg-3',
                text: 'Selam Zeynep! Dermatoloji kongresine gidecek misin?',
                senderId: 'me',
                status: 'read' as MessageStatus,
                timestamp: hoursAgo(3),
            },
            {
                id: 'msg-4',
                text: 'Evet, hazırlanıyorum! Siz de mi katılacaksınız?',
                senderId: 'them',
                status: 'read' as MessageStatus,
                timestamp: hoursAgo(2),
            },
            {
                id: 'msg-5',
                text: 'Cumartesi pilates sonrası kahve olur mu? ☕',
                senderId: 'them',
                status: 'delivered' as MessageStatus,
                timestamp: hoursAgo(1),
            },
        ],
    },
    {
        profile: DEMO_PROFILES[4], // Dr. Defne
        timestamp: daysAgo(1),
        lastMessage: 'Neonatoloji ile ilgili harika bir makale buldum, paylaşayım mı?',
        isFirstMessagePending: false,
        isActive: true,
        firstMessageSentAt: daysAgo(1),
        messages: [
            {
                id: 'msg-6',
                text: 'Merhaba Defne! Gönüllülük projelerin çok ilham verici.',
                senderId: 'me',
                status: 'read' as MessageStatus,
                timestamp: daysAgo(1),
            },
            {
                id: 'msg-7',
                text: 'Teşekkürler! Neonatoloji ile ilgili harika bir makale buldum, paylaşayım mı?',
                senderId: 'them',
                status: 'read' as MessageStatus,
                timestamp: hoursAgo(18),
            },
        ],
    },
    {
        profile: DEMO_PROFILES[6], // Dr. Selin
        timestamp: hoursAgo(6),
        isFirstMessagePending: true,
        allowedSenderId: null,
        expiresAt: hoursFromNow(18),
        isActive: true,
        messages: [],
    },
];

// ─── DEMO NOTIFICATIONS ──────────────────────────────────────────────────────

export const DEMO_NOTIFICATIONS: Notification[] = [
    {
        id: 'dn-1',
        type: NotificationType.SUPER_LIKE,
        senderProfile: DEMO_PROFILES[0],
        timestamp: minutesAgo(15),
        isRead: false,
    },
    {
        id: 'dn-2',
        type: NotificationType.MATCH,
        senderProfile: DEMO_PROFILES[2],
        timestamp: hoursAgo(3),
        isRead: false,
    },
    {
        id: 'dn-3',
        type: NotificationType.LIKE,
        senderProfile: DEMO_PROFILES[4],
        timestamp: hoursAgo(5),
        isRead: false,
    },
    {
        id: 'dn-4',
        type: NotificationType.MATCH,
        senderProfile: DEMO_PROFILES[6],
        timestamp: hoursAgo(6),
        isRead: true,
    },
    {
        id: 'dn-5',
        type: NotificationType.LIKE,
        senderProfile: DEMO_PROFILES[1],
        timestamp: daysAgo(1),
        isRead: true,
    },
];

// ─── DEMO SWIPE HISTORY ──────────────────────────────────────────────────────

export const DEMO_SWIPE_HISTORY: SwipeHistoryItem[] = [
    { id: 'dh-1', profile: DEMO_PROFILES[1], action: 'PASS', timestamp: minutesAgo(20) },
    { id: 'dh-2', profile: DEMO_PROFILES[3], action: 'LIKE', timestamp: hoursAgo(1) },
    { id: 'dh-3', profile: DEMO_PROFILES[5], action: 'PASS', timestamp: hoursAgo(4) },
    { id: 'dh-4', profile: DEMO_PROFILES[7], action: 'SUPER_LIKE', timestamp: daysAgo(1) },
    { id: 'dh-5', profile: DEMO_PROFILES[0], action: 'LIKE', timestamp: daysAgo(2) },
];

// ─── DEMO LIKES YOU ──────────────────────────────────────────────────────────

export const DEMO_LIKES_YOU: Profile[] = [
    { ...DEMO_PROFILES[0], id: 'dly-1' },
    { ...DEMO_PROFILES[2], id: 'dly-2' },
    { ...DEMO_PROFILES[4], id: 'dly-3' },
    { ...DEMO_PROFILES[6], id: 'dly-4' },
    { ...DEMO_PROFILES[1], id: 'dly-5' },
    { ...DEMO_PROFILES[3], id: 'dly-6' },
    { ...DEMO_PROFILES[5], id: 'dly-7' },
    { ...DEMO_PROFILES[7], id: 'dly-8' },
];
