// Auto-generated from Sağlık Bölümleri.xlsx — DO NOT EDIT MANUALLY
// 214 Turkish universities with their available health faculties/departments

export interface UniversityDeptEntry {
  name: string;
  departments: string[];
}

export const TURKISH_HEALTH_UNIVERSITIES: UniversityDeptEntry[] = [
  { name: "ABDULLAH GÜL ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "ACIBADEM MEHMET ALİ AYDINLAR ÜNİVERSİTESİ", departments: ["Tıp", "Eczacılık", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "ADA KENT ÜNİVERSİTESİ", departments: ["Diş Hekimliği", "Psikoloji"] },
  { name: "ADANA ALPARSLAN TÜRKEŞ BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "ADIYAMAN ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Laboratuvar"] },
  { name: "AFYON KOCATEPE ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "AFYONKARAHİSAR SAĞLIK BİLİMLERİ ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "İlk ve Acil Yardım", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "AKDENİZ ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "AKSARAY ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Sağlık Yönetimi", "Tıbbi Laboratuvar"] },
  { name: "ALANYA ALAADDİN KEYKUBAT ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "İlk ve Acil Yardım", "Tıbbi Laboratuvar"] },
  { name: "ALANYA ÜNİVERSİTESİ", departments: ["Hemşirelik", "Fizyoterapi"] },
  { name: "ALTINBAŞ ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "AMASYA ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "İlk ve Acil Yardım", "Tıbbi Laboratuvar"] },
  { name: "ANADOLU ÜNİVERSİTESİ", departments: ["Eczacılık", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Dil ve Konuşma Terapisi", "Psikoloji", "Tıbbi Laboratuvar"] },
  { name: "ANKARA BİLİM ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "ANKARA HACI BAYRAM VELİ ÜNİVERSİTESİ", departments: ["Sağlık Yönetimi", "Psikoloji"] },
  { name: "ANKARA MEDİPOL ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Odyoloji", "Dil ve Konuşma Terapisi", "Ergoterapi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "ANKARA SOSYAL BİLİMLER ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "ANKARA YILDIRIM BEYAZIT ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Odyoloji", "Dil ve Konuşma Terapisi", "Psikoloji", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "ANKARA ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Odyoloji", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "ANTALYA BELEK ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "ANTALYA BİLİM ÜNİVERSİTESİ", departments: ["Diş Hekimliği", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "ARDAHAN ÜNİVERSİTESİ", departments: ["Hemşirelik", "Sağlık Yönetimi", "İlk ve Acil Yardım", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "ARTVİN ÇORUH ÜNİVERSİTESİ", departments: ["Hemşirelik", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "İlk ve Acil Yardım", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "ATATÜRK ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri"] },
  { name: "ATILIM ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Odyoloji", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri"] },
  { name: "AVRASYA ÜNİVERSİTESİ", departments: ["Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Odyoloji", "Ergoterapi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "AYDIN ADNAN MENDERES ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri"] },
  { name: "AĞRI İBRAHİM ÇEÇEN ÜNİVERSİTESİ", departments: ["Tıp", "Eczacılık", "Hemşirelik", "Ebelik", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Laboratuvar"] },
  { name: "BAHÇEŞEHİR KIBRIS ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "BAHÇEŞEHİR ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Odyoloji", "Dil ve Konuşma Terapisi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "BALIKESİR ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Ebelik", "Fizyoterapi", "Psikoloji", "İlk ve Acil Yardım"] },
  { name: "BANDIRMA ONYEDİ EYLÜL ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Tıbbi Görüntüleme"] },
  { name: "BARTIN ÜNİVERSİTESİ", departments: ["Hemşirelik", "Ebelik", "Psikoloji", "İlk ve Acil Yardım"] },
  { name: "BATMAN ÜNİVERSİTESİ", departments: ["Diş Hekimliği", "Hemşirelik", "Sağlık Yönetimi", "İlk ve Acil Yardım", "Tıbbi Laboratuvar"] },
  { name: "BAYBURT ÜNİVERSİTESİ", departments: ["Hemşirelik", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Laboratuvar"] },
  { name: "BAŞKENT ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Odyoloji", "Dil ve Konuşma Terapisi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "BEYKOZ ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "BEZM-İ ÂLEM VAKIF ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Odyoloji", "Ergoterapi", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "BOLU ABANT İZZET BAYSAL ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Görüntüleme", "Ağız ve Diş Sağlığı"] },
  { name: "BOĞAZİÇİ ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "BURDUR MEHMET AKİF ERSOY ÜNİVERSİTESİ", departments: ["Diş Hekimliği", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "İlk ve Acil Yardım", "Anestezi", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "BURSA TEKNİK ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "BURSA ULUDAĞ ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "BİLECİK ŞEYH EDEBALİ ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Sağlık Yönetimi", "İlk ve Acil Yardım", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri"] },
  { name: "BİNGÖL ÜNİVERSİTESİ", departments: ["Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "BİRUNİ ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Odyoloji", "Dil ve Konuşma Terapisi", "Ergoterapi", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "BİTLİS EREN ÜNİVERSİTESİ", departments: ["Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "DEMİROĞLU BİLİM ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri"] },
  { name: "DOKUZ EYLÜL ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "DOĞU AKDENİZ ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "DOĞUŞ ÜNİVERSİTESİ", departments: ["Hemşirelik", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "DÜZCE ÜNİVERSİTESİ", departments: ["Tıp", "Eczacılık", "Hemşirelik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım"] },
  { name: "DİCLE ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "EGE ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Odyoloji", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri"] },
  { name: "ERCİYES ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Beslenme ve Diyetetik", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "ERZURUM TEKNİK ÜNİVERSİTESİ", departments: ["Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji"] },
  { name: "ERZİNCAN BİNALİ YILDIRIM ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "ESKİŞEHİR OSMANGAZİ ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Ebelik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "FATİH SULTAN MEHMET VAKIF ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "FENERBAHÇE ÜNİVERSİTESİ", departments: ["Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Dil ve Konuşma Terapisi", "Ergoterapi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "FIRAT ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "GAZİ ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Odyoloji", "Dil ve Konuşma Terapisi", "İlk ve Acil Yardım", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "GAZİANTEP ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "İlk ve Acil Yardım", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "GAZİANTEP İSLAM BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Ebelik", "Fizyoterapi", "İlk ve Acil Yardım", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri"] },
  { name: "GÜMÜŞHANE ÜNİVERSİTESİ", departments: ["Hemşirelik", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "GİRESUN ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Ebelik", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Laboratuvar"] },
  { name: "GİRNE AMERİKAN ÜNİVERSİTESİ", departments: ["Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Sağlık Yönetimi", "Ergoterapi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "GİRNE ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Ağız ve Diş Sağlığı"] },
  { name: "HACETTEPE ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Odyoloji", "Dil ve Konuşma Terapisi", "Ergoterapi", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "HAKKARİ ÜNİVERSİTESİ", departments: ["Hemşirelik", "İlk ve Acil Yardım", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "HALİÇ ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Dil ve Konuşma Terapisi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme"] },
  { name: "HARRAN ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Fizyoterapi", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "HASAN KALYONCU ÜNİVERSİTESİ", departments: ["Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Anestezi"] },
  { name: "HATAY MUSTAFA KEMAL ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "HOCA AHMET YESEVİ ULUSLARARASI TÜRK-KAZAK ÜNİVERSİTESİ", departments: ["Diş Hekimliği"] },
  { name: "HİTİT ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "İlk ve Acil Yardım", "Tıbbi Laboratuvar"] },
  { name: "IĞDIR ÜNİVERSİTESİ", departments: ["Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "İlk ve Acil Yardım", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "IŞIK ÜNİVERSİTESİ", departments: ["Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri"] },
  { name: "KADİR HAS ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "KAFKAS ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Ebelik", "Sağlık Yönetimi", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "KAHRAMANMARAŞ SÜTÇÜ İMAM ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Ebelik", "Fizyoterapi", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "KAHRAMANMARAŞ İSTİKLAL ÜNİVERSİTESİ", departments: ["Hemşirelik", "Beslenme ve Diyetetik", "Psikoloji"] },
  { name: "KAPADOKYA ÜNİVERSİTESİ", departments: ["Diş Hekimliği", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Odyoloji", "Dil ve Konuşma Terapisi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "KARABÜK ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Ebelik", "Fizyoterapi", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "KARADENİZ TEKNİK ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "KARAMANOĞLU MEHMETBEY ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "İlk ve Acil Yardım", "Tıbbi Görüntüleme", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "KASTAMONU ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Ebelik", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım"] },
  { name: "KAYSERİ ÜNİVERSİTESİ", departments: ["Sağlık Yönetimi", "İlk ve Acil Yardım"] },
  { name: "KIBRIS AMERİKAN ÜNİVERSİTESİ", departments: ["Anestezi"] },
  { name: "KIBRIS AYDIN ÜNİVERSİTESİ", departments: ["Hemşirelik", "Fizyoterapi", "Psikoloji", "İlk ve Acil Yardım"] },
  { name: "KIBRIS BATI ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "KIBRIS SAĞLIK VE TOPLUM BİLİMLERİ ÜNİVERSİTESİ", departments: ["Diş Hekimliği", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji", "Ağız ve Diş Sağlığı"] },
  { name: "KIRGIZİSTAN-TÜRKİYE MANAS ÜNİVERSİTESİ", departments: ["Tıp"] },
  { name: "KIRIKKALE ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "KIRKLARELİ ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "Tıbbi Laboratuvar"] },
  { name: "KIRŞEHİR AHİ EVRAN ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Ebelik", "Fizyoterapi", "İlk ve Acil Yardım", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "KOCAELİ SAĞLIK VE TEKNOLOJİ ÜNİVERSİTESİ", departments: ["Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "KOCAELİ ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Ebelik", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "KONYA GIDA VE TARIM ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "KOÇ ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Psikoloji"] },
  { name: "KTO KARATAY ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Odyoloji", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Ameliyathane Hizmetleri"] },
  { name: "KÜTAHYA DUMLUPINAR ÜNİVERSİTESİ", departments: ["Tıbbi Laboratuvar"] },
  { name: "KÜTAHYA SAĞLIK BİLİMLERİ ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Dil ve Konuşma Terapisi", "Ergoterapi", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "KİLİS 7 ARALIK ÜNİVERSİTESİ", departments: ["Hemşirelik", "Sağlık Yönetimi", "İlk ve Acil Yardım"] },
  { name: "LEFKE AVRUPA ÜNİVERSİTESİ", departments: ["Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "LOKMAN HEKİM ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Odyoloji", "Dil ve Konuşma Terapisi", "Ergoterapi", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "MALATYA TURGUT ÖZAL ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Ebelik", "Beslenme ve Diyetetik", "Psikoloji", "Tıbbi Laboratuvar"] },
  { name: "MALTEPE ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme"] },
  { name: "MANİSA CELÂL BAYAR ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Ebelik", "Fizyoterapi", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "MARDİN ARTUKLU ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Ebelik", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Laboratuvar"] },
  { name: "MARMARA ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "MEF ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "MERSİN ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri"] },
  { name: "MUDANYA ÜNİVERSİTESİ", departments: ["Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Dil ve Konuşma Terapisi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme"] },
  { name: "MUNZUR ÜNİVERSİTESİ", departments: ["Hemşirelik", "Ebelik", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "İlk ve Acil Yardım"] },
  { name: "MUĞLA SITKI KOÇMAN ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Dil ve Konuşma Terapisi", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Laboratuvar"] },
  { name: "MUŞ ALPARSLAN ÜNİVERSİTESİ", departments: ["Hemşirelik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri"] },
  { name: "NECMETTİN ERBAKAN ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "NEVŞEHİR HACI BEKTAŞ VELİ ÜNİVERSİTESİ", departments: ["Diş Hekimliği", "Hemşirelik", "Psikoloji"] },
  { name: "NUH NACİ YAZGAN ÜNİVERSİTESİ", departments: ["Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme"] },
  { name: "NİĞDE ÖMER HALİSDEMİR ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "İlk ve Acil Yardım"] },
  { name: "ONDOKUZ MAYIS ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Odyoloji", "Dil ve Konuşma Terapisi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "ORDU ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi"] },
  { name: "ORTA DOĞU TEKNİK ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "OSMANİYE KORKUT ATA ÜNİVERSİTESİ", departments: ["Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "İlk ve Acil Yardım"] },
  { name: "PAMUKKALE ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "RECEP TAYYİP ERDOĞAN ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Laboratuvar"] },
  { name: "SAKARYA UYGULAMALI BİLİMLER ÜNİVERSİTESİ", departments: ["Hemşirelik", "Fizyoterapi", "Sağlık Yönetimi", "İlk ve Acil Yardım", "Tıbbi Laboratuvar"] },
  { name: "SAKARYA ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Ebelik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "SAMSUN ÜNİVERSİTESİ", departments: ["Tıp", "Sağlık Yönetimi", "Psikoloji"] },
  { name: "SANKO ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Ameliyathane Hizmetleri"] },
  { name: "SAĞLIK BİLİMLERİ ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Odyoloji", "Dil ve Konuşma Terapisi", "Ergoterapi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "SELÇUK ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Odyoloji", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri"] },
  { name: "SÜLEYMAN DEMİREL ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "SİNOP ÜNİVERSİTESİ", departments: ["Hemşirelik", "Ebelik", "Sağlık Yönetimi", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Laboratuvar"] },
  { name: "SİVAS CUMHURİYET ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "SİİRT ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "İlk ve Acil Yardım", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "TARSUS ÜNİVERSİTESİ", departments: ["Hemşirelik", "Ebelik", "Fizyoterapi", "Sağlık Yönetimi", "Dil ve Konuşma Terapisi", "İlk ve Acil Yardım"] },
  { name: "TED ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "TEKİRDAĞ NAMIK KEMAL ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Laboratuvar"] },
  { name: "TOBB EKONOMİ VE TEKNOLOJİ ÜNİVERSİTESİ", departments: ["Tıp", "Psikoloji"] },
  { name: "TOKAT GAZİOSMANPAŞA ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "İlk ve Acil Yardım", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "TOROS ÜNİVERSİTESİ", departments: ["Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "TRABZON ÜNİVERSİTESİ", departments: ["Tıp", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "TRAKYA ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Odyoloji", "Ergoterapi", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "UFUK ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri"] },
  { name: "ULUSLARARASI BALKAN ÜNİVERSİTESİ", departments: ["Diş Hekimliği", "Psikoloji"] },
  { name: "ULUSLARARASI FİNAL ÜNİVERSİTESİ", departments: ["Diş Hekimliği", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji"] },
  { name: "ULUSLARARASI KIBRIS ÜNİVERSİTESİ", departments: ["Diş Hekimliği", "Eczacılık", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Anestezi"] },
  { name: "ULUSLARARASI SARAYBOSNA ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "UŞAK ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "VAN YÜZÜNCÜ YIL ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "YAKIN DOĞU ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Odyoloji", "Ergoterapi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "YALOVA ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Fizyoterapi", "Psikoloji", "İlk ve Acil Yardım"] },
  { name: "YAŞAR ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "YEDİTEPE ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji"] },
  { name: "YOZGAT BOZOK ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Ebelik", "Fizyoterapi", "Sağlık Yönetimi", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme"] },
  { name: "YÜKSEK İHTİSAS ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Dil ve Konuşma Terapisi", "Ergoterapi", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri"] },
  { name: "ZONGULDAK BÜLENT ECEVİT ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Fizyoterapi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "ÇANAKKALE ONSEKİZ MART ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Ebelik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "ÇANKAYA ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "ÇANKIRI KARATEKİN ÜNİVERSİTESİ", departments: ["Diş Hekimliği", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Ergoterapi", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Laboratuvar"] },
  { name: "ÇAĞ ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "ÇUKUROVA ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "ÖZYEĞİN ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "ÜSKÜDAR ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Odyoloji", "Dil ve Konuşma Terapisi", "Ergoterapi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "İBN HALDUN ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "İHSAN DOĞRAMACI BİLKENT ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "İNÖNÜ ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Odyoloji", "Dil ve Konuşma Terapisi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL 29 MAYIS ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "İSTANBUL AREL ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL ATLAS ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Dil ve Konuşma Terapisi", "Ergoterapi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL AYDIN ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Odyoloji", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL BEYKENT ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL BİLGİ ÜNİVERSİTESİ", departments: ["Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL ESENYURT ÜNİVERSİTESİ", departments: ["Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL GALATA ÜNİVERSİTESİ", departments: ["Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL GEDİK ÜNİVERSİTESİ", departments: ["Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Ameliyathane Hizmetleri"] },
  { name: "İSTANBUL GELİŞİM ÜNİVERSİTESİ", departments: ["Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Odyoloji", "Dil ve Konuşma Terapisi", "Ergoterapi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL KENT ÜNİVERSİTESİ", departments: ["Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Dil ve Konuşma Terapisi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL KÜLTÜR ÜNİVERSİTESİ", departments: ["Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji"] },
  { name: "İSTANBUL MEDENİYET ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Odyoloji", "Psikoloji"] },
  { name: "İSTANBUL MEDİPOL ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Odyoloji", "Dil ve Konuşma Terapisi", "Ergoterapi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL NİŞANTAŞI ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Dil ve Konuşma Terapisi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL OKAN ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL RUMELİ ÜNİVERSİTESİ", departments: ["Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL SABAHATTİN ZAİM ÜNİVERSİTESİ", departments: ["Hemşirelik", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji"] },
  { name: "İSTANBUL SAĞLIK VE SOSYAL BİLİMLER MESLEK YÜKSEKOKULU", departments: ["Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL SAĞLIK VE SOSYAL BİLİMLER MESLEK YÜKSEKOKULU İstanbul Sağlık ve Sosyal Bilimler Meslek Yüksekokulu", departments: ["İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Ameliyathane Hizmetleri"] },
  { name: "İSTANBUL SAĞLIK VE TEKNOLOJİ ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji", "Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL TOPKAPI ÜNİVERSİTESİ", departments: ["Hemşirelik", "Ebelik", "Ergoterapi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL TİCARET ÜNİVERSİTESİ", departments: ["Psikoloji"] },
  { name: "İSTANBUL YENİ YÜZYIL ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Psikoloji"] },
  { name: "İSTANBUL ÜNİVERSİTESİ-CERRAHPAŞA", departments: ["Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL ÜNİVERSİTESİ-CERRAHPAŞA Cerrahpaşa Tıp Fakültesi", departments: ["Tıp"] },
  { name: "İSTANBUL ÜNİVERSİTESİ-CERRAHPAŞA Diş Hekimliği Fakültesi", departments: ["Diş Hekimliği"] },
  { name: "İSTANBUL ÜNİVERSİTESİ-CERRAHPAŞA Eczacılık Fakültesi", departments: ["Eczacılık"] },
  { name: "İSTANBUL ÜNİVERSİTESİ-CERRAHPAŞA Florence Nightingale Hemşirelik Fakültesi", departments: ["Hemşirelik"] },
  { name: "İSTANBUL ÜNİVERSİTESİ-CERRAHPAŞA Sağlık Bilimleri Fakültesi", departments: ["Ebelik", "Fizyoterapi", "Sağlık Yönetimi", "Odyoloji"] },
  { name: "İSTANBUL ÜNİVERSİTESİ-CERRAHPAŞA Sağlık Hizmetleri Meslek Yüksekokulu", departments: ["Tıbbi Görüntüleme"] },
  { name: "İSTANBUL ŞİŞLİ MESLEK YÜKSEKOKULU", departments: ["Ağız ve Diş Sağlığı"] },
  { name: "İSTANBUL ŞİŞLİ MESLEK YÜKSEKOKULU İstanbul Şişli Meslek Yüksekokulu", departments: ["İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Ameliyathane Hizmetleri"] },
  { name: "İSTİNYE ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Dil ve Konuşma Terapisi", "Psikoloji", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "İZMİR BAKIRÇAY ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Fizyoterapi", "Sağlık Yönetimi", "Odyoloji", "Dil ve Konuşma Terapisi", "Psikoloji"] },
  { name: "İZMİR DEMOKRASİ ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji"] },
  { name: "İZMİR EKONOMİ ÜNİVERSİTESİ", departments: ["Tıp", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar"] },
  { name: "İZMİR KATİP ÇELEBİ ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Eczacılık", "Hemşirelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Sağlık Yönetimi", "Psikoloji", "İlk ve Acil Yardım", "Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "İZMİR KAVRAM MESLEK YÜKSEKOKULU", departments: ["Tıbbi Laboratuvar", "Ağız ve Diş Sağlığı"] },
  { name: "İZMİR KAVRAM MESLEK YÜKSEKOKULU İzmir Kavram Meslek Yüksekokulu", departments: ["İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Ameliyathane Hizmetleri"] },
  { name: "İZMİR TINAZTEPE ÜNİVERSİTESİ", departments: ["Tıp", "Diş Hekimliği", "Hemşirelik", "Ebelik", "Fizyoterapi", "Beslenme ve Diyetetik", "Odyoloji", "Dil ve Konuşma Terapisi", "Ergoterapi", "İlk ve Acil Yardım", "Anestezi", "Tıbbi Görüntüleme", "Tıbbi Laboratuvar", "Ameliyathane Hizmetleri", "Ağız ve Diş Sağlığı"] },
  { name: "İÇİŞLERİ BAKANLIĞI VE MİLLİ SAVUNMA BAKANLIĞI ADINA SAĞLIK BİLİMLERİ ÜNİVERSİTESİNDE EĞİTİM ALACAKLAR Gülhane Diş Hekimliği Fakültesi", departments: ["Diş Hekimliği"] },
  { name: "ŞIRNAK ÜNİVERSİTESİ", departments: ["Hemşirelik", "Ebelik", "Sağlık Yönetimi", "İlk ve Acil Yardım", "Tıbbi Laboratuvar"] },
];

export const UNIVERSITY_NAMES = TURKISH_HEALTH_UNIVERSITIES.map(u => u.name);

export function getDepartmentsForUniversity(name: string): string[] {
  const entry = TURKISH_HEALTH_UNIVERSITIES.find(
    u => u.name.toLowerCase() === name.toLowerCase()
  );
  return entry?.departments ?? [];
}